App setup
Mylo16/air-pollution pull request #1
Opened 2023-05-28 00:20 UTC by Mylo16

## In this PR:
- I built an air pollution mobile web app as my final capstone project in react
- The app was built with React.js, Redux, CSS, etc.
- Test files were also built 
- There are no linter errors
- The web app is a SPA
- The web app follows React and Redux best practices
- Below is the link to the description video on the mobile web app:
- https://www.loom.com/share/bc1d7ca05394435995f432141219106b

2023-05-28 05:54 UTC, Lucas-Masaba requested changes
# Hello @Mylo16  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- The design looks good :+1: 
- Descriptive README :scroll: 
- Well-written pull request message :writing_hand: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-28 05:54 UTC, Lucas-Masaba commented on README.md
> +I would like to thank the entire microverse staff and students for such a wonderful coding camp
- [ ] Please add an acknowledgement that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-05-28 05:54 UTC, Lucas-Masaba commented on src/components/Home.js
> +            <button key={pollutant.td} type="button" onClick={() => HandleDetails(pollutant)} className="pollutant">
- [ ] Please change `pollutant.td` to `pollutant.dt` because it brings an error to the console on the web browser mentioning that each item you have mapped should have a unique key prop.
![image](https://github.com/Mylo16/air-pollution/assets/45460192/98086a6a-fef2-41a4-a773-9262c8ae23bd)

2023-05-28 05:54 UTC, Lucas-Masaba commented on src/App.js
> +        <Route exact path="/details" element={<Details />} />
- [ ] When I click on an item on your home page, it takes me to its detail page with different information. However, as mentioned in the project requirements, each item detail page should have a unique route. There should be a third route that looks something like this 
``<Route exact path="/details/:id" component={Detail} />``

After you have given it a unique route, your link in `Home.js`should look something similar to this
`              <Link className="link" to="/details/:id">
`

2023-05-28 05:54 UTC, Lucas-Masaba commented on src/__tests__/store.test.js
- [ ] You have a failing test here as seen in the screenshot below.
![image](https://github.com/Mylo16/air-pollution/assets/45460192/9a9adc50-2bc0-41a1-9bf1-345e81d35907)

2023-05-28 06:45 UTC, descholar-ceo requested changes
Hi @Mylo16 🤝 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
👍🏽 Linters pass the check ✔️ 
👍🏽 Addressed almost all requirements and comments ✔️ 
👍🏽 Correct usage of git flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-28 06:45 UTC, descholar-ceo commented on src/__tests__/store.test.js
> +    expect(screen.getByText('18 : 05')).toBeInTheDocument();
- [ ] This test case is still failing, would you look into it?
<img width="1148" alt="Screenshot 2023-05-28 at 08 43 03" src="https://github.com/Mylo16/air-pollution/assets/56886064/c63bba9a-5963-43c9-a1e2-3b64dc286543">

2023-05-30 19:16 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Mylo16👋, 

### You are doing a marvelous job on the React capstone project and this is one of the best projects I have seen so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Nice UI design. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 19:16 UTC, thecodechaser commented on src/__tests__/store.test.js
> +            {
- [ ] This test is failing, Please make sure all the tests pass without any errors.

![image](https://github.com/Mylo16/air-pollution/assets/83803414/d76a321d-2ae6-4e37-ad07-6ca695777ed8)

2023-05-30 19:57 UTC, Mylo16 commented
Please check the screenshot below, the test works fine on my pc

![image](https://github.com/Mylo16/air-pollution/assets/112702953/d839a56c-9d2f-45ef-a319-a581d4b356a3)

2023-05-30 20:09 UTC, amejid approved these changes
Hi @Mylo16, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct workflow :heavy_check_mark: 
- Good UI :heavy_check_mark: 
- Failing test fixed :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 21:21 UTC, merged